# Generated by Django 3.0.8 on 2020-07-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('date', models.DateTimeField(null=True)),
                ('summary', models.TextField(max_length=5000, null=True)),
                ('userImage_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
