# Generated by Django 3.0.8 on 2020-07-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='summary',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='userImage_url',
            new_name='user_image_url',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='userName',
            new_name='user_name',
        ),
    ]
